import os
import git
from github import Github
from agent.state import AgentState, AgentStatus
import structlog

logger = structlog.get_logger()

REPOS_DIR = "repos"


def run(state: AgentState) -> AgentState:
    logger.info("github_commit_started", session_id=state["session_id"])

    try:
        repo_url = state["repo_url"]

        # Remove .git suffix for GitHub API
        clean_url = repo_url.rstrip("/")
        if clean_url.endswith(".git"):
            clean_url = clean_url[:-4]

        repo_name = clean_url.split("/")[-1]

        # Find local cloned folder — try both with and without .git
        local_path = os.path.join(REPOS_DIR, f"{state['session_id']}_{repo_name}.git")
        if not os.path.exists(local_path):
            local_path = os.path.join(REPOS_DIR, f"{state['session_id']}_{repo_name}")

        logger.info("using_local_path", path=local_path)

        local_repo  = git.Repo(local_path)
        branch_name = f"ai-dev/{state['session_id'][:8]}"

        local_repo.git.checkout("-b", branch_name)

        for change in state["file_changes"]:
            file_full_path = os.path.join(local_path, change["file_path"])
            os.makedirs(os.path.dirname(file_full_path), exist_ok=True)
            with open(file_full_path, "w", encoding="utf-8") as f:
                f.write(change["new_content"])
            logger.info("file_written", path=change["file_path"])

        local_repo.git.add("--all")

        commit_message = f"AI: {state['cleaned_intent']}\n\nChanges:\n" + \
            "\n".join(f"- {c['file_path']}" for c in state["file_changes"])

        local_repo.index.commit(commit_message)

        origin = local_repo.remote("origin")
        origin.push(branch_name)

        # Use clean URL without .git for GitHub API
        github_client = Github(state["github_token"])
        repo_full     = clean_url.replace("https://github.com/", "")

        logger.info("creating_pr", repo=repo_full, branch=branch_name)

        github_repo = github_client.get_repo(repo_full)

        pr = github_repo.create_pull(
            title=f"AI: {state['cleaned_intent']}",
            body=f"## AI Generated Changes\n\n"
                 f"**Request:** {state['cleaned_intent']}\n\n"
                 f"**Files Changed:**\n" +
                 "\n".join(f"- `{c['file_path']}`" for c in state["file_changes"]) +
                 "\n\n---\n*Generated by AI GitHub Dev*",
            head=branch_name,
            base=github_repo.default_branch
        )

        logger.info("pr_created", pr_url=pr.html_url)

        return {
            **state,
            "branch_name": branch_name,
            "pr_url":      pr.html_url,
            "status":      AgentStatus.DONE,
            "logs":        state["logs"] + [f"PR created: {pr.html_url}"]
        }

    except Exception as e:
        logger.error("github_commit_failed", error=str(e))
        return {
            **state,
            "status":        AgentStatus.FAILED,
            "error_message": f"GitHub commit failed: {str(e)}"
        }
