import os
import git
from github import Github
from agent.state import AgentState, AgentStatus
import structlog

logger = structlog.get_logger()

REPOS_DIR = 'repos'


def run(state: AgentState) -> AgentState:
    '''
    GitHub Commit node — writes files and opens PR.
    Reads:  state.file_changes, state.github_token, state.repo_url
    Writes: state.branch_name, state.pr_url, state.status
    '''
    logger.info('github_commit_started', session_id=state['session_id'])

    try:
        # Setup paths
        repo_name  = state['repo_url'].rstrip('/').split('/')[-1]
        local_path = os.path.join(
            REPOS_DIR,
            f"{state['session_id']}_{repo_name}"
        )

        # Open local repo
        local_repo    = git.Repo(local_path)
        branch_name   = f"ai-dev/{state['session_id'][:8]}"

        # Create and checkout new branch
        local_repo.git.checkout('-b', branch_name)

        # Write all generated files to disk
        for change in state['file_changes']:
            file_full_path = os.path.join(local_path, change['file_path'])

            # Create directories if needed
            os.makedirs(os.path.dirname(file_full_path), exist_ok=True)

            # Write file content
            with open(file_full_path, 'w', encoding='utf-8') as f:
                f.write(change['new_content'])

            logger.info('file_written', path=change['file_path'])

        # Stage all changes
        local_repo.git.add('--all')

        # Commit
        commit_message = f'''AI: {state["cleaned_intent"]}

Changes made:
''' + '\n'.join(f'- {c["file_path"]}' for c in state['file_changes'])

        local_repo.index.commit(commit_message)

        # Push branch to GitHub
        origin = local_repo.remote('origin')
        origin.push(branch_name)

        # Open Pull Request via GitHub API
        github_client = Github(state['github_token'])
        repo_full     = state['repo_url'].replace('https://github.com/', '')
        github_repo   = github_client.get_repo(repo_full)

        pr = github_repo.create_pull(
            title=f'AI: {state["cleaned_intent"]}',
            body=f'''## AI Generated Changes

**Request:** {state["cleaned_intent"]}

**Files Changed:**
''' + '\n'.join(f'- {c["file_path"]}' for c in state['file_changes']) + '''

---
*This PR was automatically generated by AI GitHub Dev*
''',
            head=branch_name,
            base=github_repo.default_branch
        )

        logger.info('pr_created', pr_url=pr.html_url)

        return {
            **state,
            'branch_name': branch_name,
            'pr_url':      pr.html_url,
            'status':      AgentStatus.DONE,
            'logs':        state['logs'] + [f'PR created: {pr.html_url}']
        }

    except Exception as e:
        logger.error('github_commit_failed', error=str(e))
        return {
            **state,
            'status':        AgentStatus.FAILED,
            'error_message': f'GitHub commit failed: {str(e)}'
        }
